Fix swift-tools-version formatting in Package.swift
The extra whitespace triggers this error when running `swift package dump-package`, which is causing the [validation in the Swift Package Index](https://github.com/SwiftPackageIndex/PackageList/actions/runs/21122767631/job/60738298811) to fail

```
error: 'host': horizontal whitespace sequence [U+0020] immediately preceding the version specifier is supported by only Swift ≥ 5.4; consider removing the sequence for Swift 5.3.0
error: invalid manifests at [<AbsolutePath:"/host">]
```